// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mefhdrdcwyaofevcumcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lZmhkcmRjd3lhb2ZldmN1bWN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NzE4NDAsImV4cCI6MjA2OTM0Nzg0MH0.8yXiNfdKLZmMEgRcXEAW3t1A0yk4Fk_PoRmBX77Fiho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});