// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://velythiaxuwrrylpeotx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlbHl0aGlheHV3cnJ5bHBlb3R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjg0OTkwMTcsImV4cCI6MjA0NDA3NTAxN30.LKx9RaLALgXk2sP7sSV4pLfJifcC1VfKJOQhvk9wWFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});